#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = hypridle 
exec-once = dunst
# exec-once = copyq --start-server
exec-once = systemctl --user start hyprpolkitagent
exec-once = ashell
exec-once = walker --gapplication-service
exec-once = awww-daemon
