##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }


# Custom

windowrule {
  name = copyQ
  match:class = ^(com.github.hluk.copyq)$
  float = true
  center = true
  size = 800 600
}
#
windowrule {
  name = pavucontrol
  match:class = ^(pavucontrol)$
  float = true
  center = true
  size = 800 600
}
#
windowrule {
  name = org.pulseaudio.pavucontrol
  match:class = ^(org.pulseaudio.pavucontrol)$
  float = true
  center = true
  size = 800 600
}

windowrule {
  name = nm-connection-editor
  match:class = ^(nm-connection-editor)$
  float = true
  center = true
  size = 800 600
}

windowrule {
  name = blueman-manager
  match:class = ^(blueman-manager)$
  float = true
  center = true
  size = 800 600
}

